name: Check Deprecated Methods

on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  check-deprecated-methods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y
          git --version
    
      - name: Check for Deprecated Methods
        run: |
          deprecated_methods=$(grep -r -n 'deprecated' ./*.swift | cut -d':' -f1)

          for file in $deprecated_methods; do
          echo "Arquivo: $file"
          echo 
          diff_output=$(git diff main $file)
          echo "Diff output: $diff_output"
          echo
          
          if [ -n "$diff_output" ]; then
              # Filtrar apenas as linhas modificadas (começando com + ou -) e capturar o número da linha
              # modified_lines=$(echo "$diff_output" | grep '^[+-]' | awk -F':' '{print $1}')
              # modified_lines=$(echo "$diff_output" | grep '^[+-]' | grep -Eo '^[+-][0-9]+' | cut -c 2-)
              # modified_lines=$(echo "$diff_output" | grep -E '^[+-]' | grep -Eo '^[+-][0-9]+' | cut -c 2-)
          
               # Imprime as linhas modificadas
              modified_lines=$(git diff --unified=0 main $file | grep -E '^\@\@' | grep -Eo '[0-9]+' | sed 's/^+//' | sed -n 'p;n')
              echo "Linhas modificadas:"
              echo "$modified_lines"
              
              deprecated_line_numbers=$(grep -n 'deprecated' $file | cut -d ':' -f 1)
              echo "Linha com deprecated"
              echo $deprecated_line_numbers
              
              # Imprimir a primeira ocorrência de '{'
              first_brace=$(sed -n "$(($deprecated_line_numbers + 1)),\$ { /^{/ { p; q } }" $file)
              echo "Primeira ocorrência de '{'"
              echo "$first_brace"
          
              echo "Há diffs para $file em relação à branch main"
              echo $diff_output
              exit 101
          fi
          echo "Não ha diffs"
          done
         
