name: Check Deprecated Methods

on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  check-deprecated-methods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y
          git --version
      - name: Show all diffs
        run: |
          git diff main
      - name: Check for Deprecated Methods
        run: |
          deprecated_methods=$(grep -r -n 'deprecated' ./*.swift | cut -d':' -f1)

          for method in $deprecated_methods; do
            diff_output=$(git diff main $method)
            if [ -z "$diff_output" ]; then
              echo "Não há diffs para $method em relação à branch main"
              exit 0
            fi
          done
         
